var CANVAS_WIDTH = 1920;
var CANVAS_HEIGHT = 1080;

var EDGEBOARD_X = 0;
var EDGEBOARD_Y = 0;

var FPS_TIME      = 1000/24;
var DISABLE_SOUND_MOBILE = false;
var FONT_GAME = "system-ui";
var FONT_PAYTABLE = "Arial";

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var GAME_STATE_IDLE         = 0;
var GAME_STATE_SPINNING     = 1;
var GAME_STATE_SHOW_ALL_WIN = 2;
var GAME_STATE_SHOW_WIN     = 3;

var REEL_STATE_START   = 0;
var REEL_STATE_MOVING = 1;
var REEL_STATE_STOP    = 2;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP   = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT  = 3;
var ON_DRAG_START = 4;
var ON_DRAG_END   = 5;

var REEL_OFFSET_X = 260;
var REEL_OFFSET_Y = 120;

var NUM_REELS = 5;
var NUM_ROWS = 3;
var NUM_SYMBOLS = 11;
var WILD_SYMBOL = 8;
var FREESPINS_SYMBOL = 3;
var FREESPIN_SPACE = 160;
var FREESPIN_RP_PER_L = 0.8;    // Random prize percentage
var FREESPIN_RP_PER_H = 1.2;
var NUM_PAYLINES = 20;
var SYMBOL_SIZE = 256;
var SPACE_BETWEEN_SYMBOLS = 25;
var MAX_FRAMES_REEL_EASE = 8;
var MIN_REEL_LOOPS;
var REEL_DELAY;
var REEL_START_Y = REEL_OFFSET_Y - (SYMBOL_SIZE * 3);
var REEL_ARRIVAL_Y = REEL_OFFSET_Y + (SYMBOL_SIZE * 3);
var TIME_SHOW_WIN;
var TIME_SHOW_ALL_WINS;
var MIN_BET;
var MAX_BET;
var TOTAL_MONEY;
var WIN_OCCURRENCE;
var SLOT_CASH;
var MIN_WIN;
var FREESPIN_OCCURRENCE;
var FREESPIN_SYMBOL_NUM_OCCURR;
var NUM_FREESPIN;
var COIN_BET;
var PAYTABLE_VALUES;
var BONUS_FREESPIN = 1;

var SEGMENT_ROT = 360 /20;
var TIME_ANIM_IDLE = 10000;
var MIN_FAKE_SPIN = 3;
var WHEEL_SPIN_TIMESPEED = 2600;
var ANIM_SPIN_TIMESPEED = 50;
var TIME_ANIM_WIN = 5000;
var ANIM_WIN1_TIMESPEED = 300;
var ANIM_WIN2_TIMESPEED = 50;
var LED_SPIN = 3;
var ANIM_IDLE1_TIMESPEED = 2000;
var ANIM_IDLE2_TIMESPEED = 100;
var ANIM_IDLE3_TIMESPEED = 150;

var NUM_SPIN_FOR_ADS;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;
